media:
  input: static/assets
  output: /assets
content:
  - name: blog
    label: blog
    path: content/blog
    type: collection
    filename: "{primary}.md"
    fields: [ title, date ]
    view:
      fields: [ date, primary, title, draft ]
      primary: title
      sort: [ date, title ]
      default:
        search: ''
        sort: title
        order: desc
