media:
  input: static/assets
  output: /assets
content:
  - name: pages
    label: Pages
    path: src/content/pages
    type: collection
    fields: [ title, description, pubDate, tags ]
    view:
      fields: [ title, description, pubDate, tags ]
      primary: title
      sort: [ date, title ]
      default:
        search: ''
        sort: title
        order: desc
