media:
  input: static/assets
  output: /assets
content:
  - name: content
    label: content
    path: content
    type: collection
    filename: "{primary}.md"
    fields: [ title, date ]
    view:
      primary: title
  - name: blog
    label: blog
    path: content/blog
    type: collection
    filename: "{primary}.md"
    fields: [ title, date ]
    view:
      primary: title
