media:
  input: static/assets
  output: /assets
content:
  - name: pages
    label: pages
    path: src/content/pages
    type: collection
    filename: "{primary}.md"
    view:
      fields: [ pubDate, primary, title, draft ]
      primary: title
      sort: [ date, title ]
      default:
        search: ''
        sort: title
        order: desc
